### ISSUE TITLE
Use unittest.mock if available

### ISSUE THREAD

**Issue by major** [googleapis/python-bigquery-connection#212]
#### Environment details

  - OS type and version: Fedora 36
  - Python version: 3.10.4
  - pip version: 22.0.4
  - `google-cloud-bigquery-connection` version: main branch

#### Steps to reproduce

  1. Run tests in Python 3.10
  2. Tests fail to import the deprecated `mock` module

I'll propose a PR in a moment.

**Comment by parthea** [comment]
Hi @major,
Thanks for reporting and fixing this issue! The code is generated automatically using [gapic-generator-python](https://github.com/googleapis/gapic-generator-python). I've opened a PR to propose a fix to the code generator in https://github.com/googleapis/gapic-generator-python/pull/1320.

**Comment by major** [comment]
@parthea Thanks for that! I had no idea that project existed.
